### ISSUE TITLE
Plugin Approval

### ISSUE THREAD

**Issue by NyakudyaA** [heinrichloewen/orientationMapsCreator#1]
# Problem

Please populate the wiki so that users know what they have to do before we publish it.

Please also change the plugin homepage to show the code repository rather than link it to the issues page

**Comment by heinrichloewen** [comment]
I modified the plugin homepage to show the code repository.
Furthermore I added a database dump to the repository for easy startup: `/assets/database/default_db.backup`

What is missing in the wiki to startup? There is a quite detailed description regarding the database setup already: `wiki/Database-Setup`

**Comment by pcav** [comment]
Much more clear now, thanks. As your plugin is an extension of an existing one (pgrouting), have you considered merging your work into it, rather than creating a new one?
I know this can be a hassle in the short term, but the advantages should be obvious both for developers, users, and managers.
Thanks for considering this option.

**Comment by heinrichloewen** [comment]
Thanks for the comment.
I did consider but unfortunately didn't do it from the beginning, and didn't take the time to do it, yet.
However, the plugin rather builds on functionality from pgRoutetingLayer but has a different purpose.

**Comment by pcav** [comment]
How much code is shared between the two plugins?
Thanks

**Comment by heinrichloewen** [comment]
I don't know exactly, but it won't be more than 15% I would say.
